### ISSUE TITLE
Usage sample?

### ISSUE THREAD

**Issue by roded** [snt/antora-mermaid-extension#5]
Hello,
I could use some assistance in getting this extension to work in the default Antora UI bundle and the latest Antora version.
I have the following playbook:

```
antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
site:
  title: ...
  url: /home/me/localpath
content:
  sources:
    - url: /home/me/localpath
      start_path: /home/me/localpath/docs
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
```

And this extension is installed via npm.
I can see that the mermaid script is loaded via jsdelivr but the example sequence diagram does not seem to render:

```
[mermaid]
....
sequenceDiagram
autonumber

participant a as Alice
participant b as Bob

a ->>+ b : Hello.
b -->>- a : Hi, there.
....
```

Any pointers would be great.
Thanks

P.S., I suspect that the `mermaid_initialize_options` as described in the README.md should not include the double quotes to avoid a JS error on start up.
